# Site settings 
title: "Nick Chandler"
description: "Data Scientist | Developer | Technologist"
baseurl: ""
url: "https://chandlernick.github.io"
theme: minima

# Author info
author:
  name: Nick Chandler
  email: njchandler2002@gmail.com

# Navigation links
header_pages:
  - index.md
  - research.md
  - projects.md
  - exploring.md

# for safe keeping! https://orcid.org/0009-0003-6546-2994
